title: Mioclonos
email: joan.navarrete.sanchez@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal site for Joan Navarrete Sanchez
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joannavarrete.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: joannava
github_username:  joannavarrete

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: GFM
highlighter: rouge
