# Setup
title:               Mioclonos
tagline:             ''
description:         'A simple personal website'
url:                 https://joannavarrete.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Joan Navarrete Sanchez
  url:               https://twitter.com/joannava
  email:             joan.navarrete.sanchez@gmai.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

markdown: GFM
highlighter: rouge